import { readFileSync } from "fs";
import {
  createKeyPairFromBytes,
  getAddressFromPublicKey,
  getBase58Decoder,
} from "@solana/web3.js";

async function main() {
  const keypairRaw = new Uint8Array(
    JSON.parse(
      readFileSync("Your id.json path(generated by solana cli)").toString()
    )
  );
  const keypair = await createKeyPairFromBytes(keypairRaw);

  const publicKey = await getAddressFromPublicKey(keypair.publicKey);
  const privateKey = getBase58Decoder().decode(keypairRaw);
  console.log(publicKey);
  console.log(privateKey);
}

main();
